---
- name: Ensure that mysql data dir exists
  file: path={{ jail_home.stdout }}{{ mariadb_data_dir }}
        state=directory

- name: Create ZFS data set
  zfs:  name={{ mariadb_zfs_dataset }}
        state=present
        mountpoint={{ host_mariadb_home }}

- name: Ensure that mysql home on host exists
  file: path={{ host_mariadb_home }}
        state=directory
        owner=88 group=88 mode=0750

- name: Configure jail to mount file system from host
  lineinfile: dest={{ jail_home.stdout }}/../fstab
              state=present
              line='{{ host_mariadb_home }} {{ jail_home.stdout }}{{ mariadb_data_dir }} nullfs rw'

- name: Install MariaDB binary package
  pkgng: name=mariadb100-server
         state=present
         chroot={{ jail_home.stdout }}

- name: Enable MariaDb service
  lineinfile: dest={{ jail_home.stdout }}/etc/rc.conf
              state=present
              regexp='^mysql_enable='
              line='mysql_enable=\"YES\"'

- name: Copy MariaDb config file
  template: dest={{ host_mariadb_home }}/my.cnf
            src=my.cnf.j2
            owner=88 group=88 mode=0640
  notify:
  - Restart {{ jail_name }} MariaDB

- name: Start jail
  command: /usr/local/sbin/iocage start {{ jail_uuid.stdout }}
  when: jail_created|changed

- name: Check if database is secured
  command: /usr/local/sbin/iocage exec {{ jail_uuid.stdout }} \
           /usr/local/bin/mysql -e 'use test'
  register: secure_check
  changed_when: false
  ignore_errors: true

- name: Copy MariaDB secure script to remote host
  template: src=mariadb-secure.sql.j2
            dest=/tmp/mariadb-secure.sql
  changed_when: false
  when: secure_check|success

- name: Execute secure DB server script
  shell: /usr/local/sbin/iocage exec {{ jail_uuid.stdout }} \
           /usr/local/bin/mysql mysql < /tmp/mariadb-secure.sql
  when: secure_check|success

- name: Delete secure script from remote host
  file: path=/tmp/mariadb-secure.sql
        state=absent
  changed_when: false
  when: secure_check|success
