---
- name: Create ZFS data sets
  zfs:  name={{ host_mariadb_zfs_dataset }}{{ item.path }}
        state=present
        atime={{ item.atime }}
        primarycache={{ item.primarycache }}
        logbias={{ item.logbias }}
        recordsize={{ item.recordsize }}
        mountpoint={{ host_mariadb_home }}{{ item.path }}
  with_items:
  - '{{ mariadb_datasets }}'

- name: Ensure mysql user permissions
  file: path={{ host_mariadb_home }}{{ item.path }}
        state=directory
        owner=88 group=88 mode=0750
  with_items:
  - '{{ mariadb_datasets }}'

- name: Ensure that mariadb directories exists within jail
  file: path={{ jail_home.stdout }}{{ mariadb_home }}{{ item.path }}
        state=directory
  with_items:
  - '{{ mariadb_datasets }}'

- name: Configure jail to mount file system from host
  lineinfile: dest={{ jail_home.stdout }}/../fstab
              state=present
              line='{{ host_mariadb_home }}{{ item.path }} {{ jail_home.stdout }}{{ mariadb_home }}{{ item.path }} nullfs rw'
  with_items:
  - '{{ mariadb_datasets }}'

- name: Install MariaDB binary package
  pkgng: name=mariadb100-server
         state=present
         chroot={{ jail_home.stdout }}

- name: Enable MariaDb service
  lineinfile: dest={{ jail_home.stdout }}/etc/rc.conf
              state=present
              regexp={{ item.regex }}
              line={{ item.line }}
  with_items:
  - { regex: '^mysql_enable=', line: 'mysql_enable=\"YES\"'}
  - { regex: '^mysql_dbdir=', line: 'mysql_dbdir=\"{{ mariadb_dbdir }}\"'}

- name: Fix mysql_install_db_args
  lineinfile: dest={{ jail_home.stdout }}/usr/local/etc/rc.d/mysql-server
              state=present
              regexp='^mysql_install_db_args='
              line='mysql_install_db_args=\"--basedir=/usr/local --datadir=${mysql_dbdir} --force --defaults-extra-file=${mysql_optfile}\"'

- name: Copy MariaDb config file
  template: dest={{ host_mariadb_home }}/data/my.cnf
            src=my.cnf.j2
            owner=88 group=88 mode=0640
  notify:
  - Restart {{ jail_name }} MariaDB

- name: Start jail
  command: /usr/local/sbin/iocage start {{ jail_uuid.stdout }}
  when: jail_created|changed

- name: Check if database is secured
  command: /usr/local/sbin/iocage exec {{ jail_uuid.stdout }} \
           /usr/local/bin/mysql -e 'use test'
  register: secure_check
  changed_when: false
  ignore_errors: true

- name: Copy MariaDB secure script to remote host
  template: src=mariadb-secure.sql.j2
            dest=/tmp/mariadb-secure.sql
  changed_when: false
  when: secure_check|success

- name: Execute secure DB server script
  shell: /usr/local/sbin/iocage exec {{ jail_uuid.stdout }} \
           /usr/local/bin/mysql mysql < /tmp/mariadb-secure.sql
  when: secure_check|success

- name: Delete secure script from remote host
  file: path=/tmp/mariadb-secure.sql
        state=absent
  changed_when: false
  when: secure_check|success
