---
- name: Copy pf configuration (rls rules)
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'pf.anchor.rls-jail.conf.j2'
    dest: '/etc/pf.anchor.rls-jail.{{ jail_name }}.conf'
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rls-jail conf
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '/etc/pf.anchor.rls-jail.conf'
    state: present
    line: 'include "/etc/pf.anchor.rls-jail.{{ jail_name }}.conf"'
  notify:
    - Reload pf
